config/routes.rb
Authorize::Application.routes.draw do
  match '/payments/payment', :to => 'payments#payment', :as => 'paymentspayment', :via => [:get]

  match '/payments/relay_response', :to => 'payments#relay_response', :as => 'payments_relay_response', :via => [:post]

  match '/payments/receipt', :to => 'payments#receipt', :as => 'payments_receipt', :via => [:get]

  match '/payments/aim_test', to: 'payments#aim_test', as: 'payments_aim_test', via: :post

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  layout 'authorize_net'
  helper :authorize_net
  protect_from_forgery :except => :relay_response

  # GET
  # Displays a payment form.
  def payment
    @amount = 10.00
    @sim_transaction = AuthorizeNet::SIM::Transaction.new(AUTHORIZE_NET_CONFIG['api_login_id'], AUTHORIZE_NET_CONFIG['api_transaction_key'], @amount, :relay_url => payments_relay_response_url(:only_path => false))
  end

  # POST
  # Returns relay response when Authorize.Net POSTs to us.
  def relay_response
    sim_response = AuthorizeNet::SIM::Response.new(params)
    if sim_response.success?(AUTHORIZE_NET_CONFIG['api_login_id'], AUTHORIZE_NET_CONFIG['merchant_hash_value'])
      render :text => sim_response.direct_post_reply(payments_receipt_url(:only_path => false), :include => true)
    else
      render
    end
  end
  
  # GET
  # Displays a receipt.
  def receipt
    @auth_code = params[:x_auth_code]
  end

  # POST
  def aim_test
    transaction = AuthorizeNet::AIM::Transaction.new(AUTHORIZE_NET_CONFIG['api_login_id'], AUTHORIZE_NET_CONFIG['api_transaction_key'], :gateway => :sandbox)
    credit_card = AuthorizeNet::CreditCard.new(params[:card][:number], params[:card][:expiration])
    response = transaction.purchase(params[:mount].to_f, credit_card)
    if response.success?
      redirect_to paymentspayment_path
    else
      raise "No anda nada" + AUTHORIZE_NET_CONFIG['api_login_id']
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Authorize</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/authorize_net.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Direct Post Sample App</title>
    <style>
    body {
      text-align: center;
      font-family: Helvetica;
    }
    label {
      display: block;
    }
    </style>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/payments/payment.erb
<%= form_for :sim_transaction, :url => AuthorizeNet::SIM::Transaction::Gateway::TEST do |f| %>
  <%= sim_fields(@sim_transaction) %>
  <%= label_tag 'x_amount', "Total: #{number_to_currency(@amount)}" %>
  <%= label_tag 'x_card_num', 'Credit Card Number'%>
  <%= text_field_tag 'x_card_num' %>
  <%= label_tag 'x_exp_date', 'Expiration Date (MMYY)'%>
  <%= text_field_tag 'x_exp_date' %>
  <br />
  <%= f.submit 'Purchase'%>
<% end %>
**********************************************************************************
OTHER FORM
**********************************************************************************
<%= form_for :aim_transaction, :url => payments_aim_test_path do |f| %>
  <%= label_tag :mount, "Total: " %>
  <%= text_field_tag :mount%>
  <%= label :card,:number, 'Credit Card Number'%>
  <%= text_field :card, :number %>
  <%= label_tag :card, :expiration%>
  <%= text_field :card, :expiration %>
  <br />
  <%= f.submit 'Purchase on AIM'%>
<% end %>

app/views/payments/receipt.erb
Thanks for your purchase! Your authorization code is <%=h @auth_code %>.

app/views/payments/relay_response.erb
Sorry, something went wrong, please try your transaction again.